### ISSUE TITLE
Virtual Memory 

### ISSUE THREAD

**Issue by ghost** [rellermeyer/course_os#25]
Implemented hardware translations so that it's easier to allocate and manage memory

**Comment by NULLx76** [comment]
Virtual memory kind of "works" but is in dire need of an overhaul.

The datastructures for the VAS overwrote the L1 page table, and the system only worked because we overwrote the L1 Page table _after_ the VM did. We discovered this bug by adding page table entries before we initialized the VM, we have currently just limited the amount the VM allocates (1024 instead of 4096 VAS').

I would also propose to relocate the page table to physical address 0x4000 as there is space there anyways between the IVT and the kernel start.

**Comment by NULLx76** [comment]
This is currently being worked on in the #45 branch

**Comment by NULLx76** [comment]
Resolved by #45
